"""user and refreshtoken

Revision ID: 64b583e3c9e6
Revises: b0035fba3753
Create Date: 2026-08-29 17:10:54.560102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64b583e3c9e6'
down_revision: Union[str, Sequence[str], None] = 'b0035fba3753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refreshtokens', sa.Column('token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refreshtokens', 'token')
    # ### end Alembic commands ###
